version: '3'

services:

  orchestrator:
    build:
      context: .
      dockerfile: ./Orchestrator/Dockerfile
    ports:
      - "8080:8080"
    container_name: orchesterator
    networks:
      - orchesterator
  agent:
    build:
      context: .
      dockerfile: ./Agent/Dockerfile
    deploy:
      replicas: 3
    networks:
      - orchesterator

networks:
  orchesterator: